### PR TITLE
feat(widget-demo): initial package

### PR DESCRIPTION
**Pull request by adamweeks**
This will be useful for the netlify deploys. I don't plan on putting it on the cdn unless asked specifically.
screenshot 2017-12-14 16 03 51

### CODE REVIEW

**Comment by adamweeks** [comment]
Deploy preview ready!

Built with commit 3c04f932399e1be584fa616e97c7700e5dc1f4ab

https://deploy-preview-598--hopeful-hamilton-4090b9.netlify.com

**Comment by bzang** [comment]
How do we access that in the netlify demo? The default is just the space widget

**Comment by adamweeks** [comment]
@bzang once we get this merged we can switch what netlify builds

**Comment by adamweeks** [comment]
@bzang here we go https://5a33ea6da6188f361af4bc57--hopeful-hamilton-4090b9.netlify.com/

**Comment by bzang** [comment]
The netlify demo doesn't seem to load widgets. I get this error:
```
index.js:64 Uncaught ReferenceError: ciscospark is not defined
    at t.value (index.js:64)
    at r.handleTouchTap (EnhancedButton.js:146)
    at Object.u (react-dom.production.min.js:26)
    at Object.invokeGuardedCallback (react-dom.production.min.js:25)
    at Object.invokeGuardedCallbackAndCatchFirstError (react-dom.production.min.js:25)
    at h (react-dom.production.min.js:30)
    at v (react-dom.production.min.js:32)
    at g (react-dom.production.min.js:32)
    at Array.forEach (<anonymous>)
    at y (react-dom.production.min.js:31)
```

**Comment by adamweeks** [comment]
Crap, must be some prod build thing. I'll look into it.

**Comment by adamweeks** [comment]
@bzang looks like there was an issue with the manual deploy on netlify, try this one out before we get any other merges in: https://5a3a7b784c4b931993d474de--hopeful-hamilton-4090b9.netlify.com/

**Pull request merged**
