### PR TITLE
Fix url markdown

### PR DESCRIPTION
**Pull request by adamweeks**
https://voxeolabs.atlassian.net/browse/SSDK-1776

### CODE REVIEW

**Comment by adamweeks** [comment]
Deploy preview for *hopeful-hamilton-4090b9* ready!

Built with commit 786b19d603fe8c1d82b412bafd6f67a0759ec5cc

https://deploy-preview-681--hopeful-hamilton-4090b9.netlify.com

**Comment by tahanson-cisco** [comment]
@adamweeks, is this still waiting to be deployed?

**Comment by adamweeks** [comment]
@tahanson-cisco yes, we are having some issues getting deployments going, but we are actively working on it

**Comment by adamweeks** [comment]
@tahanson-cisco the fix has been merged to master but this has been updated to just have a test to confirm the fix. You should be able to tell the client to check /latest

**Pull request merged**
